### ISSUE TITLE
list is not displaying

### ISSUE THREAD

**Issue by PhiliPdB** [cor/Wording#7]

**Comment by LeonGr** [comment]
Reason: javascript checks for URL length to see if you went back from 127.0.0.1:5001/cor/engelse_woorden to 127.0.0.1:5001/cor. But duitse_woorden is also shorter than engelse_woorden so it hides the list.

**Comment by LeonGr** [comment]
Fixed by using <url>.split('/') and comparing the length of returned array instead of total string length.
