### ISSUE TITLE
Tab to add row doesn't work on OS X

### ISSUE THREAD

**Issue by cor** [cor/Wording#9]
The tab to add row feature doesn't work on OS X
![system info](https://cloud.githubusercontent.com/assets/4728062/9900421/fdbd23aa-5c60-11e5-9ed0-4fc92d3da3e0.png)

Tested on Safari 8.0.8, Chrome 45.0.2454.93 and Firefox DE 40.0a2 (2015-06-11)

**Comment by PhiliPdB** [comment]
Seems to be fixed
